poll/urls.py
from django.urls import path

from . import views

app_name= 'poll'
urlpatterns = [
    # localhost:8000/poll
    path('', views.home, name='home'),
    # localhost:8000/poll/i/vote/
    path('<int:q_id>/vote/', views.vote, name='vote'),
    # localhost:8000/poll/i/result/
    path('<int:q_id>/result/', views.result, name='result'),
]

pollsapp/urls.py
from django.contrib import admin
from django.http import HttpResponse
from django.urls import path, include
from django.shortcuts import render


def hello(request):
    return HttpResponse('Hello Enginners ⚙')

def multiply(request, num):
    html=f'<h1>Tabla del { num }</h1>'
    for i in range(1,11):
        html += f'<p>{ i } * { num } = { i * num }</p>'
    return HttpResponse(html)  

def home(request):
    return render(request, 'home.html')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('poll/', include('poll.urls')),
    path('hello/',hello, name='hello'),
    path('table/<int:num>/',multiply, name='multiply'),
    path('', home, name='home'),

]

poll/models.py
from django.db import models

# Create your models here.

class Questions(models.Model):
    question_text = models.CharField(max_length=150)
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    choice_text = models.CharField(max_length=100)
    question = models.ForeignKey(Questions,on_delete=models.CASCADE)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

poll/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Questions, Choice

# Create( your views here.
def home(request):
    questions = Questions.objects.all()
    return render(
        request,
        'poll/home.html',
        {
            "questions":questions
        })


def vote(request, q_id):
    q = get_object_or_404(Questions, pk=q_id)
    if request.method == "POST":
        try:
            choice_id = request.POST.get('choice')
            choice = q.choice_set.get(pk=choice_id)
            choice.votes += 1
            choice.save()
            return redirect('poll:result', q_id)
        except (KeyError, Choice.DoesNotExist):
            return render(request, 'poll/vote.html', {
                "question": q,
                "error_nessage": "Debes elegir algo! XD"
            })

def result(request, q_id):
    try:
        q = Questions.objects.get(pk=q_id)
    except Questions.DoesNotExist:
        return redirect('poll:home')
    return render(request, 'poll/result.html', {
        "question": q
    })

templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Encuestas | {% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock%}
    </div>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<h1>Welcome home</h1>
<a href="{% url 'poll:home' %}">Ir a encuestas</a>
{% endblock %}

templates/poll/home.html
{% extends 'base.html' %}

{% block title %} Encuesta {% endblock %}

{% block content %}
<h1>Encuestas</h1>

<ul>
    {% for q in questions %}
    <li><a href="{% url 'poll:vote' q.id %}"> {{ q }} </a></li>
    - <a href="{% url 'poll:results' q.id % }"></a>
    {% endfor %}
</ul>
{% endblock %}

templates/poll/result.html
{% extends 'base.html' %}

{%block title  %}Resultados{% endblock %}

{% block content %}
<h1>{{ question.question_text }}</h1>
<ul>
    {% for c in question.choice_set.all}
    <li> {{ c.choice_text }} - {{ c.votes}} voto {{c.votes︱ pluralize}}</li>
    {% endfor %}
</ul>

<div class="canva" style="width: 500px; margin:0 auto;">
    <canvas id="myPieChart" width="400px" height="400px"></canvas>

  </div>
  <!-- Canvas para la gráfica de pastel -->
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script>
    const ctx = document.getElementById('myPieChart').getContext('2d');
    const choiceText = '{{ choice_text|escapejs }}';  // Convertir a JSON
    const votes = '{{ votes|escapejs }}';  // Convertir a JSON

    const chartData = {
        labels: JSON.parse(choiceText),
        datasets: [{
            label: 'Votos por Opción',
            data: JSON.parse(votes),
            backgroundColor: [
              'rgba(255, 99, 132, 0.2)',
              'rgba(54, 162, 235, 0.2)',
              'rgba(255, 206, 86, 0.2)',
              'rgba(75, 192, 192, 0.2)',
              'rgba(153, 102, 255, 0.2)',
              'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: 'rgba(75, 192, 192, 1)',
            borderWidth: 1
        }]
    };

    const myBarChart = new Chart(ctx, {
        type: 'bar',
        data: chartData,
        options: {
            responsive: true,
            plugins: {
                legend: {
                    position: 'top',
                },
                title: {
                    display: true,
                    text: 'Bar Chart of Votes'
                }
            }
        }
    });
</script>

<hr>
<a href="{% url 'poll:home' %}">Encuestas</a>
{% endblock}

templates/poll/vote.html
{% extends "base.html" %}

{% block title %}Vota{% endblock title %}

{% block content %}
    <h1>{{ question.question_text }}</h1>
    {% if error_message %}
        <div class="alert">
        <p>{{ error_message}}</p>
        </div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        {% for c in question.choice_set.all %}
        <input
            type="radio" 
            name="choice"
            id="c_{{ c.id }}"
            value="{{ c.id}}">
        <label for="c_{{ c.id}}">{{ c.choice_text}}</label>
        <br>
        {% endfor %}
        <input type="submit" value="Votar">
        </ul>
    </form>

{% endblock %}